In [1]:
# importing Libraries
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
# loading dataset
df = pd.read_csv('Drilling.csv')
df

Cutting speed  Feed rate  Delamination
0               5        0.1          1.21
1               5        0.2          1.33
2               5        0.3          1.35
3               5        0.4          1.50
4              10        0.1          1.40
5              10        0.2          1.35
6              10        0.3          1.40
7              10        0.4          1.35
8              15        0.1          1.40
9              15        0.2          1.48
10             15        0.3          1.50
11             15        0.4          1.60
12             20        0.1          1.61
13             20        0.2          1.68
14             20        0.3          1.70
15             20        0.4          1.73

In [3]:
linreg = linear_model.LinearRegression()

In [4]:
# training model
linreg.fit(df[['Cutting speed','Feed rate']],df['Delamination'])

LinearRegression()

In [5]:
# Values of coefficients
linreg.coef_

array([0.02235, 0.4475 ])

In [6]:
# value of y intercept
linreg.intercept_

1.0831250000000001

In [8]:
linreg.predict([[5,0.1]])

array([1.239625])

In [24]:
linreg.predict([[20,0.4]])

array([1.709125])